import type { Metadata } from "next";
import "./globals.css";
import ToastProvider from "../components/Toast";
import NavbarWrapper from "../components/NavbarWrapper";
import FeedbackProvider from '../components/Feedback';

// Removendo as fontes do Next.js para resolver o conflito com o Babel

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className="h-full bg-background">
      <body className="h-full font-sans bg-gray-50">
        <FeedbackProvider>
          <ToastProvider>
            <NavbarWrapper />
            <main className="min-h-screen bg-gray-50 pt-4 pb-12">
              {children}
            </main>
          </ToastProvider>
        </FeedbackProvider>
      </body>
    </html>
  );
}
